---

# <--------------------- ALLOW LIST ---------------------->
#### Badly implemented Skapa license field requires this
- - :permit
  - "SEE LICENSE IN LICENSE.md"
- - :permit
  - "SEE LICENSES IN README.md"
#### BSD Variants
- - :permit
  - 3-Clause BSD License
- - :permit
  - (AFL-2.1 OR BSD-3-Clause)
- - :permit
  - BSD
- - :permit
  - BSD 3-clause
- - :permit
  - BSD License 3
- - :permit
  - New BSD
- - :permit
  - BSD style modified by Coverity
- - :permit
  - Simplified BSD
#### Apache Variants
- - :permit
  - Apache 2.0
#### Eclipse Variants
- - :permit
  - Eclipse Distribution License - v 1.0
- - :permit
  - Eclipse Distribution License v. 1.0
- - :permit
  - EDL 1.0
#### MIT Variants
- - :permit
  - MIT
- - :permit
  - The MIT License (MIT)
- - :permit
  - MIT-0
#### Creative Commons Variants
- - :permit
  - CC0
- - :permit
  - "Public Domain, per Creative Commons CC0"
#### Other
- - :permit
  - Bouncy Castle Licence
- - :permit
  - ISC
- - :permit
  - Python-2.0
- - :permit
  - unknown
- - :permit
  - Unlicense
- - :permit
  - UNLICENSED
- - :permit
  - W3C
# <---------------------- DENY LIST ---------------------->
- - :restrict
  - AGPL-3.0
- - :restrict
  - CC-BY-NC-3.0
- - :restrict
  - SSPL-1.0
- - :restrict
  - Sleepycat
- - :restrict
  - Sun Proprietary Non Commercial License
# <-------------- AWAITING APPROVAL LIST ----------------->
- - :permit
  - Eclipse Public License 1.0
- - :permit
  - Eclipse Public License v. 2.0
- - :permit
  - Eclipse Public License - v 2.0
- - :permit
  - Eclipse Public License v2.0
- - :permit
  - EPL 2.0
- - :permit
  - MPL 2.0 or EPL 1.0
- - :permit
  - GNU Library General Public License v2.1 or later
- - :permit
  - CDDL + GPLv2 with classpath exception
- - :permit
  - GNU Lesser General Public License
- - :permit
  - GNU Lesser General Public License version 2.1
- - :permit
  - "GNU LESSER GENERAL PUBLIC LICENSE, Version 2.1"
- - :permit
  - GPLv2
- - :permit
  - GPL2 w/ CPE
- - :permit
  - Go License
# <----------- SPECIFIC DEPENDENCY APPROVALS ------------->
#### ELASTIC SEARCH CLIENT
- - :approve
  - elasticsearch
- - :approve
  - elasticsearch-cli
- - :approve
  - elasticsearch-core
- - :approve
  - elasticsearch-geo
- - :approve
  - elasticsearch-plugin-classloader
- - :approve
  - elasticsearch-rest-high-level-client
- - :approve
  - elasticsearch-secure-sm
- - :approve
  - elasticsearch-x-content
- - :approve
  - aggs-matrix-stats-client
- - :approve
  - lang-mustache-client
- - :approve
  - mapper-extras-client
- - :approve
  - parent-join-client
- - :approve
  - rank-eval-client
- - :approve
  - transport-netty4-client
